// SpaceMouseATL.idl : IDL source for SpaceMouseATL
//

// This file will be processed by the MIDL tool to
// produce the type library (SpaceMouseATL.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(FA3FB27A-D681-4DD6-A7C8-FD1426C1647F),
	version(1.0),
]
library SpaceMouseATLLib
{
	importlib("stdole2.tlb");
};

